### ISSUE TITLE
Cool mod but

### ISSUE THREAD

**Issue by ImpulsiveLass** [DarkSnakeX/NoCorpseHigherQuota#1]
Why is it only additive?

Instead of + x you could get the quota value and instead multiply it by x 
 like * x

so 1.1 would be 10% extra quota (13 added to 130) per unrecovered body

You could add a bool to make it selectable between those 2 functions, the addition by itself is not very dynamic since that can make it too strong early and too weak later.

**Comment by DarkSnakeX** [comment]
If I understand correctly you suggest that if the dynamic option is enabled, instead of sum just multiply it.
Before:
`Num += Math.Abs(days*5+totaldead*Config.Instance.Configcost-cuerposMuertosenNave*(Config.Instance.Configcost/2));`
After:
`Num *= Math.Abs(days*5+totaldead*Config.Instance.Configcost-cuerposMuertosenNave*(Config.Instance.Configcost/2));`

Is this what are you suggesting?

**Comment by ImpulsiveLass** [comment]
So you have the else to have it not increased but I'm thinking another if it trigged if the new config is enabled where its
                        TimeOfDay.Instance.profitQuota += Config.Instance.Configcost * (TimeOfDay.Instance.timesFulfilledQuota + 1);
                        Num += Config.Instance.Configcost;
                        
Unless I'm reading it backwards?

This setting should make it so that one first quota (13) each unrecovered body is configcost * 1
after passing the first and moving onto the second it will be configcost * 2 and so on
so if config cost is 30 then it will be 120 added per missing player on quota 4

**Comment by ImpulsiveLass** [comment]
Another setting could get TimeOfDay.Instance.profitQuota
from (*newconfigsettingforextrapercentincrease* * (TimeOfDay.Instance.timesFulfilledQuota + 1)) * TimeOfDay.Instance.profitQuota

So if the new config is 0.1 (10 percent of current quota) it should first multiply that by the current quotas passed then multiply that by the current profit quota so if the current quota is 1000 and the new config is set to 0.1 it should be (0.1)(5th quota)(1000) = 500
then 1000+500 per corpse so if 3 die it will add 1500 to the quota

Unless I am just skill issuing at math I hope you understand what I'm saying?

**Comment by ImpulsiveLass** [comment]
Wait you don't need to multipy by the quota value then since thats already taken into account by the curent quota so its just
(0.1)(1000)=100
so lossing 3 bodies will add 300 to the quota

**Comment by ImpulsiveLass** [comment]
since that would be 2-3 functions on top of the normal nondynamic I would replace the dynamic bool with an int that takes 1,2, and 3 if you do both those and have the if functions run the dynamic calculator if the int is 1, the added being multiplied if its 2, and the percent added by current quota if the int is 3. Else (say 0) would result in the normal linear config cost being applied

**Comment by DarkSnakeX** [comment]
Sorry but I am not understanding you correctly or I don't really understand the problem. The `if (Config.Instance.Configdynamic)` is when in the config on the game is the dynamic thing enabled and the else only sums up the corpses that died, in either cases it will increase the quota, just different ways. So I don't understand this:
> So you have the else to have it not increased

There are two ways to increase the quota(normal(not dynamic) and hard(dynamic)), making a third one is not necessary in my opinion if this is what you are finally suggesting.

**Comment by ImpulsiveLass** [comment]
The dynamic doesn’t really fill that role imo, it’s kinda weird? It seems to change day to day and is independent of the quota which will always cause imbalance. Especially so if people are playing with a mod that changes the quota

**Comment by ImpulsiveLass** [comment]
My idea would just be that it’s dynamic in the fact that it adjusts based on the quota

**Comment by DarkSnakeX** [comment]
Sorry for the late reply, I will change the formula to add the variable of the quota to be more dynamic as soon as I can. Thanks for the suggestion.

**Comment by DarkSnakeX** [comment]
Added a fix to this in the next version.
