### ISSUE TITLE
Quota get added even if i retrieve the bodies

### ISSUE THREAD

**Issue by TheRealMrKam** [DarkSnakeX/NoCorpseHigherQuota#2]
I got a bug lately, i retrieved the bodies but i noticed that the quota got added anyways.

Here is the log, not sure if it's usefull tho :

[LogOutput.log](https://github.com/DarkSnakeX/NoCorpseHigherQuota/files/14629132/LogOutput.log)

**Comment by DarkSnakeX** [comment]
As you can understand its impossible to me to read near 30k lines of log to determine where the bug can occur.
I need you to provide the next information so I can try to test it myself.
- When exactly it occurs
- Number of players you were playing
- Number of people that have died and alive
- List of mods you were using

**Comment by TheRealMrKam** [comment]
Oh sorry about that

I'm not really sure when, maybe it was happening before but i didn't notice.
We were 3. I teleported my 2 friends corpses in then died and it counted as 3 corpses not retrived insted of 1.

I'm sorry i have a ton of mods and i don't have a code for the mods because i use manual install, you can find them on the log or i can make you a list with the mod modlister if you prefer ?
